eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

microservice:
  payment-service:
    endpoints:
      fetchPaymentById:
        uri: http://PAYMENT-MICROSERVICE/payments/
        
  user-service:
    endpoints:
      fetchUserById:
        uri: http://USER-MICROSERVICE/users/
      
